---
sidebar: true
toc: false
format:
  html:
    page-layout: full
    body-width: 1000px
  
---

::: {.callout-note appearance="simple"}

## Installation Note

The current package version (v1.0.0) is not yet released on PyPI. To use the latest version, install directly from GitHub:

```bash
pip install git+https://github.com/Sherwin-14/py-mealdb.git
```

:::

# The MealDB Python Library

The MealDB Python Library provides seamless access to The MealDB API, enabling developers to integrate a rich database of meal recipes into their applications. The library is designed for Python, making it easy to incorporate meal data into your projects.

## Get Started

Before getting started make sure that you have got your API_KEY from [The Meal DB](https://www.themealdb.com/).

```py
from py_mealdb import MealDB

mb = MealDB(API_KEY)
meals = mb.get_meal_by_name('Potato Salad')
print(meals.names)        # ['Potato Salad']
print(meals[0]['strMeal']) # 'Potato Salad'
```

## Contributing
We appreciate all contributions, from reporting bugs to implementing new features. Read our contributing guide to learn more.


## License
This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0.


